package model.entities;
// Generated 25/08/2013 8:05:52 PM by Hibernate Tools 3.2.1.GA



/**
 * Genres generated by hbm2java
 */
public class Genres  implements java.io.Serializable {


     private int genreId;
     private String genre;
     private String active;

    public Genres() {
    }

     public Genres(int genreId, String genre, String active) {
       this.genreId = genreId;
       this.genre = genre;
       this.active = active;
    }
   
    public int getGenreId() {
        return this.genreId;
    }
    
    public void setGenreId(int genreId) {
        this.genreId = genreId;
    }
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }

   public String getActive() {
        return active;
    }

    public void setActive(String active) {
        this.active = active;
    }


}


