package model.entities;
// Generated 17/08/2013 10:51:39 PM by Hibernate Tools 3.2.1.GA

/**
 * Login generated by hbm2java
 */
public class Login implements java.io.Serializable {

    private int loginId;
    private String email;
    private String password;
    private String userKey;

    /*
     * Default constractor
     */
    public Login() {
    }

    /*
     * Constractor with param
     */
    public Login(String email, String password, String userKey) {

        this.email = email;
        this.password = password;
        this.userKey = userKey;
    }

    /*
     * Getter and Setter
     */
    public int getLoginId() {
        return this.loginId;
    }

    public void setLoginId(int loginId) {
        this.loginId = loginId;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUserKey() {
        return this.userKey;
    }

    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }
}
