package model.entities;


// Generated 30/08/2013 11:06:25 AM by Hibernate Tools 3.2.1.GA



/**
 * MoviesType generated by hbm2java
 */
public class MoviesType  implements java.io.Serializable {


     private int movieTypeId;
     private String movieType;
     private double price;
     private Integer stock;
     private String active;
     private Movies movie;

    

    public MoviesType() {
    }

	
    public MoviesType(int movieTypeId, String movieType, double price) {
        this.movieTypeId = movieTypeId;
        this.movieType = movieType;
        this.price = price;
    }
    public MoviesType(int movieTypeId, String movieType, double price, Integer stock, String active,Movies movie) {
       this.movieTypeId = movieTypeId;
       this.movieType = movieType;
       this.price = price;
       this.stock = stock;
       this.active = active;
       this.movie = movie;
    }
   
    public int getMovieTypeId() {
        return this.movieTypeId;
    }
    
    public void setMovieTypeId(int movieTypeId) {
        this.movieTypeId = movieTypeId;
    }
    public String getMovieType() {
        return this.movieType;
    }
    
    public void setMovieType(String movieType) {
        this.movieType = movieType;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }
    public Integer getStock() {
        return this.stock;
    }
    
    public void setStock(Integer stock) {
        this.stock = stock;
    }
    
    
    
    public String getActive() {
        return this.active;
    }
    
    public void setActive(String active) {
        this.active = active;
    }

    public Movies getMovie() {
        return movie;
    }

    public void setMovie(Movies movie) {
        this.movie = movie;
    }


}


