package model.entities;

// Generated 30/08/2013 11:05:57 AM by Hibernate Tools 3.2.1.GA
/**
 * Movies generated by hbm2java
 */
public class Movies implements java.io.Serializable {

    private int movieId;
    private String movieTitle;
    private Integer releaseYear;
    private String description;
    private String active;
    private Genres genre;
    private Integer genreId;

    /*
     * Default constractor
     */
    public Movies() {
    }


    /*
     * Constractor with param
     */
    public Movies(int movieId, String movieTitle) {
        this.movieId = movieId;
        this.movieTitle = movieTitle;
    }
    
    /*
     * Constractor with param
     */
    public Movies(int movieId, String movieTitle, Integer releaseYear, String description, String active, int genreId) {
        this.movieId = movieId;
        this.movieTitle = movieTitle;
        this.releaseYear = releaseYear;
        this.description = description;
        this.active = active;
        this.genreId = genreId;
    }

    /*
     * Getter and Setter
     */
    public int getMovieId() {
        return this.movieId;
    }

    public void setMovieId(int movieId) {
        this.movieId = movieId;
    }

    public String getMovieTitle() {
        return this.movieTitle;
    }

    public void setMovieTitle(String movieTitle) {
        this.movieTitle = movieTitle;
    }

    public Integer getReleaseYear() {
        return this.releaseYear;
    }

    public void setReleaseYear(Integer releaseYear) {
        this.releaseYear = releaseYear;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getActive() {
        return this.active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    public Integer getGenreId() {
        return genreId;
    }

    public void setGenreId(Integer genreId) {
        this.genreId = genreId;
    }

    public Genres getGenre() {
        return genre;
    }

    public void setGenre(Genres genre) {
        this.genre = genre;
    }
}
