package model.entities;
// Generated 21/09/2013 12:53:32 PM by Hibernate Tools 3.2.1.GA



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int ordersId;
     private MoviesBuy movieBuy;
     private MoviesRent movieRent;
     private Double price;
     private Users user;

    public Orders() {
    }

	
    public Orders(int ordersId) {
        this.ordersId = ordersId;
    }
    public Orders(int ordersId, MoviesBuy movieBuy, MoviesRent movieRent, Double price, Users user) {
       this.ordersId = ordersId;
       this.movieBuy = movieBuy;
       this.movieRent = movieRent;
       this.price = price;
       this.user = user;
    }
   
    public int getOrdersId() {
        return this.ordersId;
    }

    public MoviesBuy getMovieBuy() {
        return movieBuy;
    }

    public void setMovieBuy(MoviesBuy movieBuy) {
        this.movieBuy = movieBuy;
    }

    public MoviesRent getMovieRent() {
        return movieRent;
    }

    public void setMovieRent(MoviesRent movieRent) {
        this.movieRent = movieRent;
    }
    
    public void setOrdersId(int ordersId) {
        this.ordersId = ordersId;
    }
 
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }

    public MoviesBuy getMoviesBuy() {
        return movieBuy;
    }

    public void setMoviesBuy(MoviesBuy movieBuy) {
        this.movieBuy = movieBuy;
    }

    public MoviesRent getMoviesRent() {
        return movieRent;
    }

    public void setMoviesRent(MoviesRent movieRent) {
        this.movieRent = movieRent;
    }

    public Users getUser() {
        return user;
    }

    public void setUser(Users user) {
        this.user = user;
    }
   




}


