package model.entities;
// Generated 27/09/2013 11:53:52 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

    private int ordersId;
    private Movies movie;
    private String type;
    private String code;
    private Integer typeId;
    private Date date;
    private Integer userId;
    private Double price;

    /*
     * Default constractor
     */
    public Orders() {
    }

    /*
     * Constractor with param
     */
    public Orders(int ordersId) {
        this.ordersId = ordersId;
    }

    /*
     * Constractor with param
     */
    public Orders(int ordersId, Movies movie, String type,String code, Integer typeId, Date date, Integer userId, Double price) {
        this.ordersId = ordersId;
        this.movie = movie;
        this.type = type;
        this.code = code;
        this.typeId = typeId;
        this.date = date;
        this.userId = userId;
        this.price = price;
    }

    /*
     * Getter and Setter
     */
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }
    
    
    public int getOrdersId() {
        return this.ordersId;
    }

    public void setOrdersId(int ordersId) {
        this.ordersId = ordersId;
    }

    public Movies getMovie() {
        return movie;
    }

    public void setMovie(Movies movie) {
        this.movie = movie;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getTypeId() {
        return this.typeId;
    }

    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }
}
