package model.entities;
// Generated 17/08/2013 10:51:39 PM by Hibernate Tools 3.2.1.GA

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

    private int userId;
    private String firstName;
    private String lastName;
    private String phoneNumber;
    private String address;
    private String active;
    private Login login;
    private Roles role;

    /*
     * Default constractor
     */
    public Users() {
    }

    /*
     * Constractor with param
     */
    public Users(String firstName, String lastName, String phoneNumber, String address, String active, Login login, Roles role) {

        this.firstName = firstName;
        this.lastName = lastName;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.active = active;
        this.login = login;
        this.role = role;
    }

    /*
     * Getter and Setter
     */
    public String getActive() {
        return active;
    }

    public void setActive(String active) {
        this.active = active;
    }

    public Roles getRole() {
        return role;
    }

    public void setRole(Roles role) {
        this.role = role;
    }

    public Login getLogin() {
        return login;
    }

    public void setLogin(Login login) {
        this.login = login;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
}
